# This is a basic workflow to help you get started with Actions

name: CI - Prod Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flux-sample-app
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_BRANCH: ${{ steps.vars.outputs.short_ref }}
        run: |
          docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH-$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH-latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH-$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Change template
        env:
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_BRANCH: ${{ steps.vars.outputs.short_ref }}
        run: |
          mkdir checkout-flux-config
          sed -i 's/<TAG_IMAGE_VERSION>/'"$GITHUB_BRANCH"'-'"$IMAGE_TAG"'/g' flux-config/helm-release-flux-sample-app-template.yaml

      - name: Checkout_flux_config
        uses: actions/checkout@v2
        with:
          repository: akaua/flux-gitops-k8s
          path: './checkout-flux-config'
          ref: 'main'

      - name: Move file to checkout path
        env:
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_BRANCH: ${{ steps.vars.outputs.short_ref }}
        run: |
          cp flux-config/helm-release-flux-sample-app-template.yaml checkout-flux-config/clusters

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'checkout-flux-config'
          destination-github-username: 'akaua'
          destination-repository-name: 'flux-gitops-k8s'
          target-branch: 'main'
          user-email: ${{ secrets.USER_EMAIL }}
          commit-message: "[ci skip] deploy from ${{ steps.vars.outputs.short_ref }}"